spring.application.name=tillgungsplan




# Text messages
messages.error.title=Fehler
messages.error.invalid_input=Einige angegebene Werte sind nicht valid, eine Berechnung des Tillgungsplans ist leider nicht moeglich!
messages.error.try_again=Bitte versuchen Sie es noch mal!
messages.result.no_elements=Es gibt kein Ergebnis zu zeigen. Bitte versuch es noch mal.
messages.result.back_to_home_page=Zurück zum Home Page
messages.result.last_element=Zinsbindungsende
messages.result.title=Result page
