spring.application.name=tilgungsplan_rechner

# Starting date of Tilgung
tilgung.starting_date=30.11.2015

# Text messages
messages.error.title=Fehler
messages.error.invalid_input=Einige angegebene Werte sind nicht valid, eine Berechnung des Tillgungsplans ist leider nicht moeglich!
message.error.inconsistent_parameters=Aus diesen parameters wird sich ein inkonsistenter Tilgungsplan ergeben. Bitte geben die erneut.
messages.error.try_again=Bitte versuchen Sie es noch mal!
messages.result.no_elements=Es gibt kein Ergebnis zu zeigen. Bitte versuch es noch mal.
messages.result.back_to_home_page=Zurueck zum Home Page
messages.result.last_element=Zinsbindungsende
messages.result.title=Result page
